import 'dart:io';

import 'package:path/path.dart' as p;

import 'icon_identifiers.dart';
import 'svg_export.dart';

/// Parses `lib/generated/iconify_icons.g.dart` from a prior subset.
Map<String, String> loadIconifiesConstMap(
  Directory projectDir, {
  String iconsPath = 'lib/generated/iconify_icons.g.dart',
}) {
  final file = File(p.join(projectDir.path, iconsPath));
  if (!file.existsSync()) return {};
  final map = <String, String>{};
  final re = RegExp(
    r'''static const (\w+) = IconifyIconRef\('([^']+)',\s*'([^']+)'\);''',
  );
  for (final m in re.allMatches(file.readAsStringSync())) {
    map[m.group(1)!] = iconId(m.group(2)!, m.group(3)!);
  }
  return map;
}

/// Generates `lib/generated/iconify_icons.g.dart` with typed [IconifyIconRef]s.
String generateIconifyIconsDart(Iterable<String> iconIds) {
  final entries = iconIds.map(parseIconId).whereType<(String, String)>().toList()
    ..sort((a, b) => iconRefFieldName(a.$1, a.$2).compareTo(iconRefFieldName(b.$1, b.$2)));

  final buffer = StringBuffer('''
// GENERATED by iconify_subset — do not edit by hand.
// ignore_for_file: constant_identifier_names

import 'package:iconify_full/iconify_full.dart';

/// Typed Iconify icons used in this app (subset of your references).
class Iconifies {
  const Iconifies._();
''');

  for (final (prefix, name) in entries) {
    final field = iconRefFieldName(prefix, name);
    buffer.writeln(
      "  static const $field = IconifyIconRef('$prefix', '$name');",
    );
  }

  buffer.writeln('}');
  return buffer.toString();
}
