import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'icon_identifiers.dart';
import 'svg_export.dart';

/// Lists exportable icon names in an IconifyJSON [set] (icons + alias keys).
Set<String> listIconNamesInSet(Map<String, dynamic> set) {
  final icons = set['icons'];
  if (icons is! Map) return {};
  return {
    ...icons.keys.cast<String>(),
    ...(set['aliases'] is Map
        ? (set['aliases'] as Map).keys.cast<String>()
        : <String>[]),
  };
}

/// Generates one Dart file per icon set under [outDir].
Future<CatalogCodegenResult> generateIconifyCatalog({
  required Directory cacheDir,
  required Directory outDir,
  List<String>? onlyPrefixes,
  void Function(String message)? log,
}) async {
  void info(String msg) => log?.call(msg);

  final jsonDir = Directory(p.join(cacheDir.path, 'json'));
  if (!jsonDir.existsSync()) {
    throw StateError(
      'No json/ in cache at ${cacheDir.path}. Run iconify_download first.',
    );
  }

  if (outDir.existsSync()) {
    for (final entity in outDir.listSync()) {
      if (entity is File && entity.path.endsWith('.dart')) {
        entity.deleteSync();
      }
    }
  } else {
    await outDir.create(recursive: true);
  }

  var jsonFiles = jsonDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.json'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  if (onlyPrefixes != null && onlyPrefixes.isNotEmpty) {
    final allow = onlyPrefixes.toSet();
    jsonFiles = jsonFiles
        .where((f) => allow.contains(p.basenameWithoutExtension(f.path)))
        .toList();
  }

  final exports = <String>[];
  var totalIcons = 0;

  for (final jsonFile in jsonFiles) {
    final prefix = p.basenameWithoutExtension(jsonFile.path);
    final set = jsonDecode(await jsonFile.readAsString()) as Map<String, dynamic>;
    final names = listIconNamesInSet(set).toList()..sort();
    if (names.isEmpty) continue;

    final className = prefixToDartClassName(prefix);
    final fileName = '${prefix.replaceAll('-', '_')}.dart';
    final outFile = File(p.join(outDir.path, fileName));

    final usedFields = <String, int>{};
    final buffer = StringBuffer('''
// GENERATED by iconify_codegen — do not edit by hand.
// iconify_prefix: $prefix
// ignore_for_file: constant_identifier_names

import 'package:iconify_full/iconify_full.dart';

/// All icons in the `$prefix` set (${names.length} icons).
class $className {
  const $className._();
''');

    for (final name in names) {
      var field = dartFieldName(name);
      final count = (usedFields[field] ?? 0) + 1;
      usedFields[field] = count;
      if (count > 1) field = '${field}_$count';

      buffer.writeln(
        "  static const $field = IconifyIconRef('$prefix', '$name');",
      );
    }

    buffer.writeln('}');
    await outFile.writeAsString(buffer.toString());
    exports.add("export '${fileName.replaceAll(r'\', '/')}';");
    totalIcons += names.length;
    info('  $prefix → $className (${names.length} icons)');
  }

  final barrelPath = p.join(outDir.path, 'iconify_catalog.dart');
  await File(barrelPath).writeAsString('''
// GENERATED by iconify_codegen — barrel export for all generated sets.
// ignore_for_file: directives_ordering

${exports.join('\n')}
''');

  return CatalogCodegenResult(
    setCount: exports.length,
    iconCount: totalIcons,
    outDir: outDir,
    barrelFile: File(barrelPath),
  );
}

/// Loads `ClassName.field` → `prefix:name` from generated catalog files.
Map<String, String> loadCatalogIconRefMap(Directory catalogDir) {
  if (!catalogDir.existsSync()) return {};
  final map = <String, String>{};
  final classRe = RegExp(
    r'''static const (\w+) = IconifyIconRef\('([^']+)',\s*'([^']+)'\);''',
  );

  for (final entity in catalogDir.listSync()) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    if (p.basename(entity.path) == 'iconify_catalog.dart') continue;

    final content = entity.readAsStringSync();
    final prefixMatch = RegExp(r'// iconify_prefix: (\S+)').firstMatch(content);
    if (prefixMatch == null) continue;
    final prefix = prefixMatch.group(1)!;
    final className = prefixToDartClassName(prefix);

    for (final m in classRe.allMatches(content)) {
      final field = m.group(1)!;
      map['$className.$field'] = iconId(m.group(2)!, m.group(3)!);
    }
  }
  return map;
}

class CatalogCodegenResult {
  const CatalogCodegenResult({
    required this.setCount,
    required this.iconCount,
    required this.outDir,
    required this.barrelFile,
  });

  final int setCount;
  final int iconCount;
  final Directory outDir;
  final File barrelFile;
}
