/// Writes `lib/generated/iconify_manifest.g.dart` for subset and init.
String generateIconifyManifestDart(
  Map<String, String> manifest, {
  String generatedBy = 'iconify_subset',
  String? extraHeaderComment,
}) {
  final entries = manifest.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));
  final buffer = StringBuffer();
  buffer.writeln('// GENERATED by $generatedBy — do not edit by hand.');
  if (extraHeaderComment != null) {
    for (final line in extraHeaderComment.split('\n')) {
      buffer.writeln('// $line');
    }
  }
  buffer.writeln('// ignore_for_file: constant_identifier_names');
  buffer.writeln();
  buffer.writeln('/// Maps Iconify ids (`prefix:name`) to bundled asset paths.');
  buffer.writeln('const Map<String, String> kIconifyManifest = {');
  for (final e in entries) {
    buffer.writeln("  '${e.key}': '${e.value}',");
  }
  buffer.writeln('};');
  buffer.writeln();
  buffer.writeln('/// Resolves an asset path for [id], or null if not in the subset.');
  buffer.writeln('String? iconifyAssetFor(String id) => kIconifyManifest[id];');
  return buffer.toString();
}

/// Empty starter manifest so apps compile before the first subset.
String generateStarterManifestDart() => generateIconifyManifestDart(
      {},
      generatedBy: 'iconify_init',
      extraHeaderComment: '''
Starter file — no icons bundled yet.
1. Add IconifyIcon('mdi:home') (etc.) under lib/
2. dart run iconify_full:iconify_download  (once, for cache)
3. dart run iconify_full:iconify_subset     (fills this file + assets/)
Register in main.dart: registerIconifyManifest(iconifyAssetFor);''',
    );
